### ISSUE TITLE
Brak pakietu na PyPI

### ISSUE THREAD

**Issue by marcinn** [mpasternak/django-interval-field#14]
Hej,

Chyba od dłuższego czasu nie ma dostępnego pakietu na https://pypi.python.org/pypi/django-pgsql-interval-field/

Są szanse, aby wrócił? :)

**Comment by mpasternak** [comment]
:+1: https://pypi.python.org/packages/2.7/d/django-pgsql-interval-field/django_pgsql_interval_field-0.9.4-py2-none-any.whl#md5=689898a5213c18a72881c418a5dc851c

https://pypi.python.org/packages/source/d/django-pgsql-interval-field/django-pgsql-interval-field-0.9.4.tar.gz#md5=a36953dbd5e4e4c38995cd839beb4cdc

**Comment by marcinn** [comment]
:beer:
